config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'games#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :games, only: [ :new, :create, :show, :update ] do
    resources :clues, only: :create
    resources :messages, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clue.rb
class Clue < ApplicationRecord
  belongs_to :game
  belongs_to :user
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :player_one, class_name: "User", optional: true
  belongs_to :player_two, class_name: "User", optional: true
  serialize :words, Array
  has_many :clues
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :game
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  has_many :games_as_player_one, source: :games, foreign_key: :player_one
  has_many :games_as_player_two, source: :games, foreign_key: :player_two
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

      def configure_permitted_parameters
          devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :nickname)}
      end
end

app/controllers/clues_controller.rb
class CluesController < ApplicationController

    def create
        @game = Game.find(params[:game_id])
        @clue = Clue.new(clue_params)
        @clue.game = @game
        @clue.user = current_user
        if @clue.save
            respond_to do |format|
                format.html
                format.json { render json: { success: true } }
            end
            # redirect_to game_path(@game) 
            
        else
            render json: { success: false }, status: :unprocessable_entity
        end
        GameChannel.broadcast_to(
            @game,
            "<p class='player-one-#{@game.player_one_id == @clue.user_id}'>#{@clue.user.nickname}: #{@clue.word_clue}</p>"
        )
    end

    private

    def clue_params
        params.require(:clue).permit(:word_clue)
    end
end


# "#{@clue.user.nickname}: #{@clue.word_clue}"

app/controllers/games_controller.rb
class GamesController < ApplicationController

    def show
        @game = Game.find(params[:id])
        @clue = Clue.new
    end
    
    def new
        @game = Game.new
    end

    def create
        @game = Game.new
        @game.words = Word.generate_word_list
        @game.player_one = current_user
        @game.player_one.color = "red"
        @game.player_two = User.all.reject{ |user| user == current_user}.first
        @game.player_two.color = "blue"
        @game.save
        redirect_to game_path(@game)
    end

    def update(game_id, params)
        @game = Game.find(id = game_id)
        @game.update(params)
    end
    
    private

    def game_params
        params.require(:game).permit(:words)
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

    def create
        @game = Game.find(params[:game_id])
        @message = Message.new(messages_params)
        @message.game = @game
        @word = Word.find(id = @message.word_id)
        @word.reveal
        words = @game.words
        new_words = words.map{ |word| word == @word ? @word : word }
        @game.update({ words: new_words})
        if @message.save
            respond_to do |format|
                format.html
                format.json { render json: { success: true } }
            end
            
        else
            render json: { success: false }, status: :unprocessable_entity
        end
        GameChannel.broadcast_to(
            @game,
            { content: @message.content, word_id: @message.word_id }
        )
    end

    private

    def messages_params
        params.require(:message).permit(:content, :word_id)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clues/_clue.html.erb
<div class="clue-container" id="clue-<%= clue.id %>">
    <p> <%= clue.word_clue %></p>
</div>

app/views/games/new.html.erb
<div class="container d-flex new-game-container align-items-center justify-content-center">
    <div class="row">
        <div class="col-4">
            <%= simple_form_for(@game) do |f| %>
                <%= f.submit class: "btn btn-primary big-btn", value: "Allez, on joue là !"%>
            <% end %>
        </div>
    </div>
</div>

app/views/games/show.html.erb
<div class="container">

    <div class="row justify-content-center cards-container">
        <% @game.words.each do |word| %>
            <% if current_user == @game.player_one %>
                <div id="<%= word.id %>" data-word="<%= word.content %>" class="col-md-5ths word-card <%= word.color %>-card <%= word.color %>-to-guess <%= word.color %>-revealed-<%= word.revealed %>">
                    <p><%= word.content %></p>
                </div>
            <% else %>
                <div id="<%= word.id %>" data-word="<%= word.content %>" class="col-md-5ths word-card <%= word.color %>-card <%= word.color %>-revealed-<%= word.revealed %>">
                    <p><%= word.content %></p>
                </div>
            <% end %>
        <% end %>
    </div>
    <div class="row">
        <div class="col-6">
            <div class="clues-container">
                <div id="clues" class="chat-container" data-game-id="<%= @game.id %>">
                    <% @game.clues.each do |clue| %>
                        <div class="clue-container" id="clue-<%= clue.id %>">
                            <p class="player-one-<%= @game.player_one_id == clue.user_id %>"><%= clue.user.nickname %>: <%= clue.word_clue %></p>
                        </div>
                    <% end %>
                </div>
            </div>
            <div class="clue">
                <%= simple_form_for [ @game, @clue ],  remote: true do |f| %>
                    <%= f.input :word_clue, label: false, placeholder: "Tape ton message" %>
                    <%= f.submit id:"form-submit", class: "btn btn-primary send-message", value: "Envoyer"  %>
                <% end %>
            </div>
        </div>
        <div class="col-6">
            <div class="messages-container">
                <div id="messages" class="chat-container" data-game-id="<%= @game.id %>">
                    <% @game.messages.each do |message| %>
                        <div class="message-container" id="message-<%= message.id %>">
                            <p><%= message.content %></p>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>
<%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %>
<%= link_to "Créer une nouvelle partie", new_game_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codenames</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>